[package]
name = "rust_shopify_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.22", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = {version = "1.0.219", features = ["derive"]}
csv = "1.3.1"
chrono = "0.4.41"